---
kind: pipeline
name: arch-kernel-package

steps:
- name: build
  image: archlinux/base
  pull: always
  volumes:
    - name: build-products
      path: /tmp/products
  commands:
    - pacman --noconfirm -Syyu
    - pacman --noconfirm --needed -S base-devel sudo
    - useradd builduser -m
    - passwd -d builduser
    - printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers # passwordless sudo
    - chown -R builduser:builduser ./
    - sudo -u builduser gpg --recv-keys 38DBBDC86092693E
    - sudo -u builduser bash -c 'export MAKEFLAGS=-j14 && makepkg -s --noconfirm'
    - ls -lah *.pkg.tar.xz
    - cp *.pkg.tar.xz /tmp/products
  trigger:
    branch:
      - master
      - 5.1-testing
    event:
      - tag

- name: sign
  image: plugins/gpgsign
  volumes:
    - name: build-products
      path: /tmp/products
  settings:
    key:
      from_secret: signing_key
    passphrase:
      from_secret: signing_key_password
    files:
      - /tmp/products/*
    armor: false
    detach_sign: true
  trigger:
    branch:
      - master
      - 5.1-testing
    event:
      - tag

- name: publish-server-testing
  image: appleboy/drone-scp
  volumes:
    - name: build-products
      path: /tmp/products
  settings:
    host: tel.aunali1.com
    username:
      from_secret: ingress_user
    password:
      from_secret: ingress_password
    port: 22
    rm: true
    strip_components: 2
    target: /srv/ftp/ingress/mbp-testing
    source:
      - /tmp/products/*
  trigger:
    branch:
      - 5.1-testing
    event:
      - tag

- name: update-repo-testing
  image: appleboy/drone-ssh
  volumes:
    - name: build-products
      path: /tmp/products
  settings:
    host: tel.aunali1.com
    username:
      from_secret: ingress_user
    password:
      from_secret: ingress_password
    port: 22
    script:
      - ./update_mbp_repo_testing.sh
  trigger:
    branch:
      - 5.1-testing
    event:
      - tag

volumes:
- name: build-products
  temp: {}
