kind: pipeline
name: arch-package

steps:
- name: build
  image: archlinux/base
  pull: always
  environment:
    MAKEFLAGS: -j14
  commands:
    - pacman --noconfirm -Syyu
    - pacman --noconfirm --needed -S base-devel sudo
    - useradd builduser -m
    - passwd -d builduser
    - printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers # passwordless sudo
    - chown -R builduser:builduser ./
    - sudo -u builduser gpg --recv-keys 38DBBDC86092693E
    - sudo -u builduser makepkg -s --noconfirm
